Brainstorm/Controllers/BrainstormController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Brainstorm.Models;
using Brainstorm.Repository;
using Brainstorm.Repository.Database;
using Brainstorm.ViewModel;
using Brainstorm.Traducoes;
using Microsoft.Owin.Security.Provider;
using Brainstorm = Brainstorm.Models.ReuniaoBrainstorm;
using System.IO;
using System.Text;
using Brainstorm.Ideia;
using Newtonsoft.Json;
using System.Net.Http;
using System.Configuration;
using System.Data.SqlClient;

namespace Brainstorm.Controllers
{
    public class BrainstormController : Controller
    {
        IIntervenientes repo = new IntervenientesDB();

        // GET: Brainstorm
        public ActionResult Reuniao()
        {

            //if (Session["utilizador_codigo"] != null)
            //{
            //    var ut = Session["utilizador_codigo"].ToString();
            //}

            Sessoes();

            var reuniaoBrainstorm = new ReuniaoBrainstorm();
            var intervenientes = new List<Interveniente>();

            //var ut = Session["utilizador_codigo"].ToString();
            //reuniaoBrainstorm.Utilizador_alt = ut;
            //var temas = new List<Tema>();
            intervenientes = repo.getUT();          

             List<Tema> temas = new List<Tema>(new Tema[10]);

            var viewModel = new BrainstormViewModel
            {
                ReuniaoBrainstorm = reuniaoBrainstorm,
                Intervenientes = intervenientes,
                Temas = temas

            };

           // repo.GetUt();

            return View(viewModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Reuniao(BrainstormViewModel model)
        {
            Sessoes();
            if(model.Temas[0].Id == null && model.ReuniaoBrainstorm.Estado == "A")
            {
                //IIntervenientes repo = new IntervenientesDB();
                var intervenientes = new List<Interveniente>();
                intervenientes = repo.getUT();
                model.Intervenientes = intervenientes;

                if(model.ReuniaoBrainstorm.Estado == "A")
                    model.ReuniaoBrainstorm.Estado = "P";
                //TempData["Erro"] = "Erro";


                TempData["EmptyTema"] = "EmptyTema";
               

                return View("Reuniao", model);
            }
            // valida campos
            if (!ModelState.IsValid)
                    {
                        //IIntervenientes repo = new IntervenientesDB();
                        var intervenientes = new List<Interveniente>();
                        intervenientes = repo.getUT();
                        model.Intervenientes = intervenientes;

                        if (model.ReuniaoBrainstorm.Estado == "Pendente")
                        {
                            model.ReuniaoBrainstorm.Estado = "P";
                        }
                        else if (model.ReuniaoBrainstorm.Estado == "Aprovado")
                        {
                            model.ReuniaoBrainstorm.Estado = "A";
                        }
                        else if (model.ReuniaoBrainstorm.Estado == "Encerrado")
                        {
                            model.ReuniaoBrainstorm.Estado = "E";
                        }

                        else if (model.ReuniaoBrainstorm.Estado == "Anulada")
                        {
                            model.ReuniaoBrainstorm.Estado = "X";
                        }
                        if (model.ReuniaoBrainstorm.Estado == "A")
                           model.ReuniaoBrainstorm.Estado = "P";

                        if (model.ReuniaoBrainstorm.Estado == "E")
                            model.ReuniaoBrainstorm.Estado = "A";

                        TempData["Erro"] = "Erro";

                        //if(model.Temas == null)
                        //{
                        //    TempData["EmptyTema"] = "EmptyTema";
                        //}

                        return View("Reuniao", model);
                    }
          
            // nova reuniao
            if (model.ReuniaoBrainstorm.Id == 0)
            {
                BrainstormRepository brainRepo = new BrainstormDB();
                var ut = Session["utilizador_codigo"].ToString();

                // inicializa estado para pendente
                model.ReuniaoBrainstorm.Estado = "P";
                //inicializa utilizador que ins/alt e data de ins/alt.
                model.ReuniaoBrainstorm.Utilizador_ins = ut;
                model.ReuniaoBrainstorm.Data_ins = DateTime.Now.ToString("dd/MM/yyyy HH:mm:ss");
                model.ReuniaoBrainstorm.Utilizador_alt = ut;
                model.ReuniaoBrainstorm.Data_alt = DateTime.Now.ToString("dd/MM/yyyy HH:mm:ss");
                // split do codigo e nome
                model.Intervenientes = tratarInterv2(model.IntervenientesView);

                // guardar dados recebidos pelo utilizador aquando da criação da reuniao com os dados preenchidos na form////////////

                DataRow id = brainRepo.guardarReuniao(model);
                int idBrainstorm = int.Parse(id[0].ToString());

                // guardar intervenientes consoante o numero de intervenientes presentes no model
                for (int i = 0; i < model.Intervenientes.Count; i++)
                {
                    DataRow idIntervenienteAux = brainRepo.guardarInterveniente(model.Intervenientes[i], idBrainstorm);
                    int idInterveniente = int.Parse(idIntervenienteAux[0].ToString());
                   
                }

                // guardar temas consoante o numero de temas presentes no model
                for (int i = 0; i < model.Temas.Count; i++)
                {
                    // estado pendente como default-- mudar a logica depois de falar com rui
                    if (model.Temas[i].Comentarios != null || model.Temas[i].Descricao != null || model.Temas[i].Titulo != null /*|| model.Temas[i].Comentarios != null*/)
                    {
                        model.Temas[i].Estado = "P";
                        DataRow idTemaAux = brainRepo.guardarTema(model.Temas[i], idBrainstorm);
                        int idTema = int.Parse(idTemaAux[0].ToString());
                        model.Temas[i].Id = idTema;
                    }
                }

                // guardar estado da reuniao (falta guardar utlizador que modifica estado, usar sessions?)
                // ver hora em que é alterado o estado
                string data = DateTime.Now.ToString("dd/MM/yyyy HH:mm:ss");
                DataRow estadoSeq = brainRepo.guardarEstado(model.ReuniaoBrainstorm.Estado, data, idBrainstorm, ut);

                TempData["additionalData"] = "Reunião criada com sucesso";
                //return RedirectToAction("Reuniao");
                return RedirectToAction("EditarReuniao", new {id = idBrainstorm});
            }
            else
            {
                // update reuniao
                 BrainstormRepository brainRepo = new BrainstormDB();
                IIntervenientes repo = new IntervenientesDB();
                var ut = Session["utilizador_codigo"].ToString();
                             
               

                //if (model.ReuniaoBrainstorm.Estado == "E")
                //{
                //    model.Intervenientes = tratarInterv2(model.IntervenientesView);

                //    brainRepo.alterarReuniao(model, model.ReuniaoBrainstorm.Id);

                //    repo.deleteIntervenientes(model.ReuniaoBrainstorm.Id);
                //    for (int i = 0; i < model.Intervenientes.Count; i++)
                //    {
                //        DataRow idIntervenienteAux = brainRepo.guardarInterveniente(model.Intervenientes[i], model.ReuniaoBrainstorm.Id);
                //        int idInterveniente = int.Parse(idIntervenienteAux[0].ToString());

                //    }

                //    // guardar temas consoante o numero de temas presentes no model
                //    for (int i = 0; i < model.Temas.Count; i++)
                //    {
                //        // se existe tema onde, comentarios, descricao =! null etc faço update
                //        if (model.Temas[i].Id != null)
                //        {
                //            if (model.Temas[i].Comentarios != null || model.Temas[i].Descricao != null || model.Temas[i].Titulo != null /*|| model.Temas[i].Comentarios != null*/)
                //            {
                //                model.Temas[i].Estado = "P";
                //                //DataRow idTemaAux = brainRepo.guardarTema(model.Temas[i], model.ReuniaoBrainstorm.Id);
                //                //int idTema = int.Parse(idTemaAux[0].ToString());
                //                //model.Temas[i].Id = idTema;
                //                brainRepo.alterarTema(model.Temas[i], model.ReuniaoBrainstorm.Id);

                //                //if (model.Temas[i].Actividade)
                //                //{
                //                //    brainRepo.gerarActividade(model.Temas[i],tabelaID,ut);
                //                //}
                //            }
                //        }
                //        // se novo tema inserir na base de dados
                //        else
                //        {
                //            if (model.Temas[i].Comentarios != null || model.Temas[i].Descricao != null || model.Temas[i].Titulo != null /*|| model.Temas[i].Comentarios != null*/)
                //            {
                //                DataRow idTemaAux = brainRepo.guardarTema(model.Temas[i], model.ReuniaoBrainstorm.Id);
                //                int idTema = int.Parse(idTemaAux[0].ToString());
                //                model.Temas[i].Id = idTema;
                //            }

Brainstorm/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    @using Brainstorm.Traducoes
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    <script src="~/Scripts/moment.js"></script>
    <script src="~/Scripts/bootstrap-datetimepicker.min.js"></script>
    <script src="~/Scripts/select2.js"></script>
    <script src="~/Scripts/JavaScript.js"></script>
    <script src="~/Scripts/DataTables/jquery.dataTables.min.js"></script>
    <script src="~/Scripts/DataTables/dataTables.bootstrap.min.js"></script>
    <script src="~/Scripts/dropzone/dropzone.min.js"></script>
    <script src="~/Scripts/bootbox.min.js"></script>
    <script src="~/Scripts/toastr.min.js"></script>
    <script src="~/Scripts/jquery.signalR-2.2.2.min.js"></script>
    <script src="~/signalr/hubs"></script>
    <link href="~/Content/bootstrap-datetimepicker.min.css" rel="stylesheet" />
    <link href="~/Content/css/select2.min.css" rel="stylesheet" />
    <link href="~/Content/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Scripts/dropzone/basic.min.css" rel="stylesheet" />
    <link href="~/Scripts/dropzone/dropzone.min.css" rel="stylesheet" />
    <link href="~/Content/DataTables/css/dataTables.bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/toastr.min.css" rel="stylesheet" />


    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header pull-right" id="navBarRight">
                @if (HttpContext.Current.Request.RequestContext.RouteData.Values["action"].ToString() == "Reuniao" || HttpContext.Current.Request.RequestContext.RouteData.Values["action"].ToString() == "EditarReuniao" || HttpContext.Current.Request.RequestContext.RouteData.Values["action"].ToString() == "EditarReuniaoNotificacao")
                {
                    <a href="@Url.Action("Reuniao", "Brainstorm")" title=@Traducoes.Traduz("Nova")>
                        <span><i class="fa fa-plus navbar-toggle" style="color:#9d9d9d;text-shadow: 0 -1px 0 rgba(0,0,0,.25);"></i></span> @*<b>Home</b>*@
                    </a>
                    @*<a href="#" title=@Traducoes.Traduz("Retroceder")>
                        <span><i class="fa fa-arrow-left navbar-toggle" style="color:#9d9d9d;text-shadow: 0 -1px 0 rgba(0,0,0,.25);"></i></span>
                    </a>*@
                    <a href="@Url.Action("GestaoBrainstorm", "Brainstorm")" title=@Traducoes.Traduz("Pesquisa")>
                        <span><i class="fa fa-search navbar-toggle" style="color:#9d9d9d;text-shadow: 0 -1px 0 rgba(0,0,0,.25);"></i></span>
                    </a>
                }
                 @if (HttpContext.Current.Request.RequestContext.RouteData.Values["action"].ToString() == "GestaoBrainstorm")
                {
                    <a href="@Url.Action("Reuniao", "Brainstorm")" title=@Traducoes.Traduz("Nova")>
                        <span><i class="fa fa-plus navbar-toggle" style="color:#9d9d9d;text-shadow: 0 -1px 0 rgba(0,0,0,.25);"></i></span> @*<b>Home</b>*@
                    </a>
                    @*<a href="javascript:history.back()" title=@Traducoes.Traduz("Retroceder")>
                        <span><i class="fa fa-arrow-left navbar-toggle" style="color:#9d9d9d;text-shadow: 0 -1px 0 rgba(0,0,0,.25);"></i></span>
                    </a>*@
                    @*<a href="#" title=@Traducoes.Traduz("Pesquisa")>
                        <span><i class="fa fa-search navbar-toggle" style="color:#9d9d9d;text-shadow: 0 -1px 0 rgba(0,0,0,.25);"></i></span>
                    </a>*@
                }
            </div>
            <div class="navbar-header pull-left">
                <a href="#" onclick="location.href='@Session["url"].ToString()index_principal.asp'" title=@Traducoes.Traduz("Home")>
                    <span><i class="fa fa-home navbar-toggle" style="color:#9d9d9d;text-shadow: 0 -1px 0 rgba(0,0,0,.25);"></i></span> @*<b>Home</b>*@
                </a>
            </div>
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div style="margin-left:10px;margin-right:10px" class="container-fluid body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Sistrade Software Consulting, SA</p>
        </footer>
    </div>




    @*<script>
            @{
                /*selecionados*/
                if (Model.IntervenientesSelecionados != null)
                {
                    var j = 1;
                    foreach (var interv in Model.IntervenientesSelecionados)
                    {
                        var id = "Interveniente" + j.ToString();
                        @:$("@id").val("@interv.NomeAndCodigo").trigger("change");
                        j++;
                    }
                }

            }
        </script>*@

</body>

</html>